### ISSUE TITLE
Does not build on kernel 5.17/Fedora 36

### ISSUE THREAD

**Issue by adalinesimonian** [UnitedRPMs/broadcom-wl-dkms#5]
```
/var/lib/dkms/broadcom-wl/6.30.223.271/build/src/wl/sys/wl_linux.c:3317:26: error: implicit declaration of function ‘PDE_DATA’; did you mean ‘NODE_DATA’? [-Werror=implicit-function-declaration]
```

This patch fixes the issue: https://gist.github.com/joanbm/37fd0590f30b41e7e89ade6e242ca16e

**Comment by sergiomb2** [comment]
also available in rpmfusion https://pkgs.rpmfusion.org/cgit/nonfree/wl-kmod.git/
